In [1]:
import numpy as np
from base import Particle
from superellipsoid import SuperEllipsoid

import sys
sys.path.append(r'/mnt/Edisk/andrew/Self_learning_MC')
from utils import *
from pytorch3d import transforms
from scipy import optimize



In [18]:
from packing import Packing

packing = Packing()

packing.particle_type = 'ellipsoid'
packing.num_particles = 2

packing.dim = 3
packing.particles = [SuperEllipsoid(2., 1., 1., 1.) for i in range(packing.num_particles)]

for i, particle in enumerate(packing.particles):
    particle.name = 'superellipsoid %d' % i
    particle.color = np.array([0.51,0.792,0.992])

packing.particles[0].centroid = np.array([0., 0., 0.])
packing.particles[1].centroid = np.array([1., 1., 1.])

f = f'ellipsoid.xyz'
packing.output_xyz(f, repeat=False)

from utils import Transform
y = Transform().mat2qua(packing.particles[0].rot_mat, "JPL")

k = np.array([-2, -6, -2])
#packing.particles[0].check(k)

packing.particles[0].support_func(k)

7.483314773547883

In [19]:
from superellipsoid import min_d
min_d(packing.particles[0], packing.particles[1])
f = f'ellipsoid1.xyz'
packing.output_xyz(f, repeat=False)

1.0


2.0

In [18]:
from superellipsoid import config_dis, resolve_overlap
x0 = np.ones(9)
res = optimize.minimize(lambda x: config_dis(x, packing.particles[0], packing.particles[1]), x0, method='SLSQP')
res.x
resolve_overlap(res.x, packing.particles[0], packing.particles[1])

In [39]:
from superellipsoid import config_dis

x0 = np.ones(9)*2.
optimize.minimize(lambda x: config_dis(x, packing.particles[0], packing.particles[1]), x0, method='SLSQP')

     fun: 5.156388491616472e-07
     jac: array([-1.06587974e-04,  8.49815928e-05,  8.49814685e-05,  6.31870859e-05,
       -4.63998366e-05, -4.63975887e-05,  6.31904453e-05, -4.64006829e-05,
       -4.64028065e-05])
 message: 'Optimization terminated successfully'
    nfev: 170
     nit: 17
    njev: 17
  status: 0
 success: True
       x: array([0.85393997, 2.87108649, 2.87108643, 0.59037382, 2.54062736,
       2.54062727, 0.59037384, 2.54062738, 2.54062735])

In [4]:
temp = v1.T - np.matmul(u.T, packing.particles[0].rot_mat)
temp

array([0., 0., 0.])

In [24]:
#rot_mat_new = packing.particles[0].rot_mat + np.matmul(u, temp.T) / (np.linalg.norm(u)**2.)
col = u.reshape(-1, 1)
row = temp.reshape(1, -1)
cc = np.matmul(col, row)
cc

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
gg = np.array([3,2,1])
ff = np.diag(np.ones(3))
ff[0][1] = 1
np.matmul(gg, ff)

array([3., 5., 1.])

In [40]:
u = np.array([1, 1, 1])
v = np.array([1, 1, 1])
col = u.reshape(-1, 1)
row = v.reshape(1, -1)
np.matmul(col, row)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])